files:
  - source: /core/res/res/values/strings.xml
    translation: /core/res/res/values-%android_code%/%original_file_name%
    translate_content: 0
  - source: /packages/SystemUI/res/values/du_strings.xml
    translation: /packages/SystemUI/res/values-%android_code%/%original_file_name%
